'use strict';
const $ = s => document.querySelector(s);
const audio = $('#audio');
const app = {library:null, selected:null, playing:null, view:'downloaded', show:null, limit:30, loop:null, timerEnd:null, token:'', dirty:false, selection:0, jobs:new Map(), jobRecords:[], focus:false, language:'both', follow:true, subtitleNodes:[], activeSubtitle:null, polling:false};
try{const language=localStorage.getItem('subtitle-language');if(['en','zh','both'].includes(language))app.language=language;}catch{}
const escapeHTML = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function clock(value){const n=Math.max(0,Math.floor(value||0));return `${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toString().padStart(2,'0')}`;}
function parseClock(value){const parts=value.trim().split(':');if(!/^\d+(?::[0-5]?\d){0,2}$/.test(value.trim()))throw Error('时间请填写为 分:秒，例如 12:30');return parts.reduce((n,p)=>n*60+Number(p),0);}
let toastTimeout;
function toast(message,error=false){const node=$('#toast');node.textContent=message;node.classList.toggle('error',error);node.hidden=false;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>node.hidden=true,error?7000:3500);}
async function api(path,data){const response=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':app.token},body:JSON.stringify(data)}:{cache:'no-store'});const body=await response.json();if(!response.ok)throw Error(body.error||'操作失败');return body;}
function guard(fn){return async(...args)=>{try{return await fn(...args);}catch(e){toast(e.message,true);}};}
function getEpisode(key){return app.library?.episodes.find(e=>e.key===key);}
function basePayload(item){return {key:item.key,asset:item.asset};}
const showStyles={waveform:{name:'Waveform',initials:'WV',theme:''},petapixel:{name:'PetaPixel',initials:'PP',theme:'photography'},gamescast:{name:'Kinda Funny Gamescast',initials:'KF',theme:'gaming'}};
function showName(id){return app.library?.shows.find(s=>s.id===id)?.name||showStyles[id]?.name||id;}
function showStyle(id){return showStyles[id]||{name:id,initials:id.slice(0,2).toUpperCase(),theme:''};}
function coverFor(id){return app.library?.shows.find(s=>s.id===id)?.cover;}
function art(id){const s=showStyle(id),cover=coverFor(id);return `<div class="episode-art ${s.theme}">${cover?`<img src="${escapeHTML(cover)}" alt="" loading="lazy">`:escapeHTML(s.initials)}</div>`;}
function setFocus(active){if(active&&!app.selected?.downloaded)return;app.focus=active;document.body.classList.toggle('focus-mode',active);$('#exit-focus').hidden=!active;$('#focus-btn').hidden=!app.selected?.downloaded;history.replaceState(null,'',active?'#listen='+encodeURIComponent(app.selected.key):location.pathname);if(active){document.querySelector('[data-tab="transcript"]').click();syncSubtitle(true);}window.scrollTo({top:0,behavior:'instant'});}
$('#exit-focus').onclick=()=>setFocus(false);$('#focus-btn').onclick=guard(async()=>{await activate(app.selected);setFocus(true);});
$('#open-playing').onclick=guard(async()=>{if(app.playing){await selectEpisode(app.playing.key);setFocus(true);}});
function downloadJob(key){return app.jobRecords.find(j=>j.show+':'+j.episode===key&&j.kind==='download'&&['queued','running'].includes(j.status));}
function rowAction(e){const job=downloadJob(e.key);return e.downloaded?`<button class="row-download" data-row-play="${escapeHTML(e.key)}" aria-label="播放 ${escapeHTML(e.title)}">▶ 播放</button>`:`<button class="row-download" data-download="${escapeHTML(e.key)}" ${job?'disabled':''} aria-label="下载 ${escapeHTML(e.title)}">${job?(job.status==='queued'?'排队中':'下载中…'):'↓ 下载'}</button>`;}
function updateDownloadState(){const d=app.selected;if(!d)return;const job=downloadJob(d.key);$('#listen-btn').disabled=!!job&&!d.downloaded;if(!d.downloaded)$('#listen-btn').textContent=job?(job.status==='queued'?'等待下载':'正在下载…'):'↓ 下载本集';}
async function queueDownload(key){const ep=getEpisode(key);if(!ep)throw Error('找不到这期节目');if(ep.downloaded){toast('这一期已经保存在本机');return;}await api('/api/job',{kind:'download',show:ep.show,episode:key.split(':')[1]});toast('已加入下载队列，完成后会出现在「已下载」');await pollJobs();}

async function loadLibrary(){app.library=await api('/api/library');app.token=app.library.token;$('#download-count').textContent=app.library.episodes.filter(e=>e.downloaded).length;$('#all-count').textContent=app.library.episodes.length;$('#mark-count').textContent=app.library.bookmarks.length;
  $('#show-nav').innerHTML=app.library.shows.map(s=>`<button class="nav-item show-nav ${app.show===s.id?'active':''}" data-show="${escapeHTML(s.id)}" title="${escapeHTML(s.category)}">${s.cover?`<img class="nav-cover" src="${escapeHTML(s.cover)}" alt="" loading="lazy">`:''}<span>${escapeHTML(showName(s.id))}</span></button>`).join('');$('#show-filter').innerHTML='<option value="">全部节目</option>'+app.library.shows.map(s=>`<option value="${escapeHTML(s.id)}">${escapeHTML(showName(s.id))}</option>`).join('');$('#show-filter').value=app.show||'';renderList();await refreshVocabulary();}

function renderList(){if(!app.library)return;if(app.view==='vocabulary'){renderVocabularyLibrary();return;}$('#search').placeholder='找一集想听的';document.querySelector('.list-heading>span:last-child').textContent='节目 / 时长';const names={downloaded:'已下载',all:'全部单集',bookmarks:'我的片段'};$('#breadcrumb').textContent=app.show?showName(app.show):names[app.view];$('#page-title').textContent=app.view==='bookmarks'?'留下的声音。':app.show?showName(app.show):app.view==='downloaded'?'接着，听下去。':'今天听什么？';
  const count=app.library.episodes.filter(e=>e.downloaded).length;$('#page-caption').textContent=app.view==='bookmarks'?'回到那句话，再听一次。':app.show?app.library.shows.find(s=>s.id===app.show)?.category:`${app.library.shows.length} 档关注 · ${count} 期已下载`;
  document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===app.view&&!app.show));
  const query=$('#search').value.trim().toLowerCase();let rows;
  if(app.view==='bookmarks'){
    rows=app.library.bookmarks.filter(b=>{const e=getEpisode(b.episode);return e&&(!app.show||e.show===app.show)&&(!query||`${e.title} ${b.note}`.toLowerCase().includes(query));});
    $('#episodes').innerHTML=rows.slice(0,app.limit).map(b=>{const e=getEpisode(b.episode);return `<button class="episode-row" data-open-mark="${b.id}">${art(e.show)}<div class="episode-info"><span class="show-name">${escapeHTML(showName(e.show))} · ${clock(b.start)}—${clock(b.end)}</span><strong>${escapeHTML(b.note||'再听听这一段')}</strong><div class="episode-meta">${escapeHTML(e.title)}</div></div><span class="row-arrow">↗</span></button>`;}).join('');
  }else{
    rows=app.library.episodes.filter(e=>(app.view!=='downloaded'||e.downloaded)&&(!app.show||e.show===app.show)&&(!query||`${e.title} ${e.show_title} ${e.search_notes}`.toLowerCase().includes(query)));
    $('#episodes').innerHTML=rows.slice(0,app.limit).map(e=>`<div class="episode-row episode-with-action ${app.selected?.key===e.key?'selected':''}"><button class="episode-select" data-episode="${escapeHTML(e.key)}">${art(e.show)}<div class="episode-info"><span class="show-name">${escapeHTML(showName(e.show))}</span><strong>${escapeHTML(e.title)}</strong><div class="episode-meta"><span>${escapeHTML(e.date)}</span><span>${Math.round(e.duration/60)} 分钟</span><span class="${e.downloaded?'downloaded':''}">${e.downloaded?(e.position>5?`已听至 ${clock(e.position)}`:'✓ 已下载'):'待下载'}</span>${e.has_transcript?'<span>有文字稿</span>':''}</div></div></button>${rowAction(e)}</div>`).join('');
  }
  $('#list-count').textContent=`${rows.length} ${app.view==='bookmarks'?'个片段':'期节目'}`;$('#more').hidden=rows.length<=app.limit;
  if(!rows.length)$('#episodes').innerHTML=`<div class="empty"><strong>${query?'没有找到匹配内容':app.view==='bookmarks'?'还没有标记':'这里还没有已下载的单集'}</strong>${query?'换个关键词试试。':app.view==='bookmarks'?'播放时点「标记这一段」，留下想再听的一段。':'在「全部单集」选择一期，点击下载。'}</div>`;
}

async function saveNotes(silent=false){const item=app.selected;if(!item?.asset||!app.dirty)return;const notes=$('#notes').value;$('#note-status').textContent='保存中…';try{await api('/api/state',{...basePayload(item),notes});item.state.notes=notes;if(app.selected?.key===item.key&&$('#notes').value===notes){app.dirty=false;$('#note-status').textContent='已保存在本机';}if(!silent)toast('笔记已保存');}catch(e){$('#note-status').textContent='保存失败，请重试';throw e;}}
async function selectEpisode(key){await saveNotes(true);const seq=++app.selection;const detail=await api('/api/episode?key='+encodeURIComponent(key));if(seq!==app.selection)return;if(app.selected?.key!==key){$('#transcript-search').value='';$('#transcript-content').scrollTop=0;}app.selected=detail;app.dirty=false;renderDetail();renderList();}

function renderDetail(){const d=app.selected;if(!d)return;$('#detail-empty').hidden=true;$('#detail').hidden=false;$('#detail-show').textContent=showName(d.show);$('#detail-title').textContent=d.title;$('#detail-state').textContent=d.downloaded?'已下载':'尚未下载';const ep=getEpisode(d.key);$('#detail-date').textContent=[ep?.date,ep?.duration?Math.round(ep.duration/60)+' 分钟':''].filter(Boolean).join(' / ');const cover=coverFor(d.show);$('#detail-cover').hidden=!cover;$('#detail-cover-fallback').hidden=!!cover;if(cover)$('#detail-cover').src=cover;$('#focus-btn').hidden=!d.downloaded;$('#listen-btn').textContent=d.downloaded?(app.playing?.key===d.key&&!audio.paused?'Ⅱ 暂停':d.state.position>5?'▶ 继续听':'▶ 开始听'):'↓ 下载本集';$('#mark-btn').disabled=!d.downloaded;$('#notes').disabled=!d.downloaded;$('#save-notes').disabled=!d.downloaded;$('#import-btn').disabled=!d.downloaded;$('#notes').value=d.state.notes||'';$('#note-status').textContent=d.downloaded?'保存在本机':'下载后可以记笔记';$('#description').textContent=d.description||'发布者没有提供简介';const source=d.source_url;if(source?.startsWith('https://')){$('#source').href=source;$('#source').hidden=false;}else $('#source').hidden=true;renderMarks();renderTranscript();renderVocabulary();updateDownloadState();}
function renderMarks(){const d=app.selected;$('#detail-mark-count').textContent=`${d.bookmarks.length} 个`;$('#detail-bookmarks').innerHTML=d.bookmarks.length?d.bookmarks.map(b=>`<div class="mark-item"><div class="mark-top"><button class="mark-time" data-jump="${b.start}">${clock(b.start)}—${clock(b.end)}</button><button class="text-button" data-loop="${b.id}">循环听</button><button class="text-button" data-delete="${b.id}" aria-label="删除 ${clock(b.start)} 的标记">删除</button></div><p>${escapeHTML(b.note||'留给下一次的自己。')}</p></div>`).join(''):'<div class="mark-empty">遇到喜欢或没听清的表达，点一下「标记这一段」。<br>先接着听，复习可以晚一点。</div>';}
function transcriptionJob(){return app.jobRecords.find(j=>j.show+':'+j.episode===app.selected?.key&&['transcribe','translate'].includes(j.kind)&&['queued','running'].includes(j.status));}
function updateTranscriptionState(){const d=app.selected;if(!d)return;const job=transcriptionJob(),tr=d.transcript,zh=tr?.translation;$('#transcribe-btn').disabled=!d.downloaded||!!job;$('#transcribe-btn').textContent=tr?'重新识别并翻译':'生成中英字幕';$('#generate-subtitles').disabled=!d.downloaded||!!job;$('#generate-subtitles').textContent=job?'正在生成字幕…':'生成中英字幕';$('#subtitle-empty-action').hidden=!!tr;$('#translate-btn').hidden=!tr||zh?.status==='succeeded';$('#translate-btn').disabled=!!job;$('#translate-btn').textContent=zh?.completed?'继续补齐中文':'生成中文翻译';$('#cancel-transcribe').hidden=!job;const stages={checking:'准备音频',loading:'准备识别',transcribing:'识别英文',translating:'翻译中文',translated:'双语字幕已保存'};let message='';if(job)message=job.status==='queued'?'已排队，稍等片刻。':`${stages[job.stage]||'准备字幕'} · ${job.progress||0}%`;else if(!d.downloaded)message='下载本集后，可以生成中英字幕。';else if(zh?.status==='waiting_key')message='英文已保存。在翻译设置中填写密钥，即可补齐中文。';else if(zh?.status==='failed')message=`中文已保存 ${zh.completed}/${zh.total} 句，可在字幕操作中继续。`;else if(tr&&zh?.status!=='succeeded'){const e=zh?.estimate;message=zh?.completed?`中文已保存 ${zh.completed}/${zh.total} 句。`:e?`翻译本期估算 ¥${e.cny_low.toFixed(2)}–${e.cny_high.toFixed(2)}，以实际用量为准。`:'';}$('#transcribe-progress').textContent=message;}
function renderTranscript(){const d=app.selected,tr=d.transcript,node=$('#transcript-content'),scroll=node.scrollTop;updateTranscriptionState();$('#transcript-search').hidden=!tr;$('#transcript-downloads').hidden=!tr;const lang=app.language;document.querySelectorAll('[data-language]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.language===lang)));node.className='language-'+lang;$('#export-txt').href='/api/transcript-export?format=txt&language='+lang+'&key='+encodeURIComponent(d.key);$('#export-srt').href='/api/transcript-export?format=srt&language='+lang+'&key='+encodeURIComponent(d.key);$('#export-srt').hidden=!tr?.aligned;$('#transcript-status').textContent=tr?(tr.translation?.status==='succeeded'?'中英字幕已保存 · 点击句子回听':tr.source==='local_asr'?'英文已保存 · 点击句子回听':'导入的英文稿'):'本期还没有字幕';if(!tr){node.innerHTML='<div class="empty"><strong>让声音，也变成文字。</strong>生成后可逐句回听，切换中英文。</div>';app.subtitleNodes=[];app.activeSubtitle=null;return;}const query=$('#transcript-search').value.toLowerCase();node.innerHTML=tr.segments.map((s,cueIndex)=>({...s,cueIndex})).filter(s=>!query||`${s.text} ${s.zh||''}`.toLowerCase().includes(query)).map(s=>{const copy=`<span class="subtitle-copy">${lang!=='zh'?`<span class="subtitle-en">${highlightVocabulary(s.text,s.cueIndex,'en')}</span>`:''}${lang!=='en'?`<span class="subtitle-zh ${s.zh?'':'subtitle-pending'}">${highlightVocabulary(s.zh||'中文待翻译',s.cueIndex,'zh')}</span>`:''}</span>`;return tr.aligned&&s.start!==null?`<div class="transcript-line" data-cue-index="${s.cueIndex}" data-start="${s.start}" data-end="${s.end}"><button class="time" data-jump="${s.start}" aria-label="回听 ${clock(s.start)}">${clock(s.start)}</button>${copy}</div>`:`<div class="transcript-line" data-cue-index="${s.cueIndex}"><span class="time"></span>${copy}</div>`;}).join('')||'<div class="empty">没有找到这句话</div>';node.scrollTop=scroll;app.subtitleNodes=[...node.querySelectorAll('[data-start]')];app.activeSubtitle=null;syncSubtitle(false);}
function syncSubtitle(scroll=true){
  if(app.playing?.key!==app.selected?.key)return;
  const nodes=app.subtitleNodes,t=audio.currentTime;let lo=0,hi=nodes.length-1,index=-1;
  while(lo<=hi){const mid=(lo+hi)>>1;if(Number(nodes[mid].dataset.start)<=t){index=mid;lo=mid+1;}else hi=mid-1;}
  const node=index>=0&&t<Number(nodes[index].dataset.end)?nodes[index]:null;
  if(node!==app.activeSubtitle){app.activeSubtitle?.classList.remove('active');app.activeSubtitle=node;node?.classList.add('active');}
  if(!node||!scroll||!app.follow||$('#tab-transcript').hidden||app.selecting||Date.now()<(app.followAfter||0)||hasSubtitleSelection())return;
  const pane=$('#transcript-content'),rect=node.getBoundingClientRect(),area=pane.getBoundingClientRect();
  const visibleHeight=Math.max(60,Math.min(area.bottom,document.querySelector('.player').getBoundingClientRect().top-8,innerHeight)-area.top);
  if(rect.top<area.top+10||rect.top>area.top+visibleHeight*.5){
    pane.scrollTo({top:pane.scrollTop+rect.top-area.top-visibleHeight*.28,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
  }
}
$('#follow-subtitles').textContent='自动滚动';
$('#follow-subtitles').onclick=()=>{app.follow=!app.follow;app.followAfter=0;$('#follow-subtitles').setAttribute('aria-pressed',String(app.follow));$('#follow-subtitles').textContent=app.follow?'自动滚动':'自由浏览';syncSubtitle(true);};
for(const event of ['wheel','touchmove'])$('#transcript-content').addEventListener(event,()=>{app.followAfter=Date.now()+6000;},{passive:true});

async function saveProgress(){const item=app.playing;if(!item||audio.readyState===0)return;const position=audio.currentTime,speed=audio.playbackRate;try{await api('/api/state',{...basePayload(item),position,speed});const ep=getEpisode(item.key);if(ep)ep.position=position;item.state.position=position;if(app.selected?.key===item.key)app.selected.state.position=position;$('#progress-status').textContent=`已记住 ${clock(position)}`;$('#progress-status').classList.remove('error');}catch(e){$('#progress-status').textContent='进度保存失败';$('#progress-status').classList.add('error');}}
async function activate(item,position=null,play=false){if(!item.downloaded)throw Error('请先下载本集');if(app.playing?.asset!==item.asset){await saveProgress();audio.pause();app.playing=item;app.loop=null;$('#loop').hidden=true;audio.src='/media?key='+encodeURIComponent(item.key);audio.load();await new Promise((resolve,reject)=>{const done=()=>{cleanup();resolve();},fail=()=>{cleanup();reject(Error('音频加载失败，请检查本地文件'));},timeout=setTimeout(fail,12000);function cleanup(){clearTimeout(timeout);audio.removeEventListener('loadedmetadata',done);audio.removeEventListener('error',fail);}audio.addEventListener('loadedmetadata',done,{once:true});audio.addEventListener('error',fail,{once:true});});audio.playbackRate=item.state.speed||1;$('#speed').value=String(audio.playbackRate);audio.currentTime=Math.min(position??item.state.position??0,Number.isFinite(audio.duration)?audio.duration:Infinity);$('#player-title').textContent=item.title;$('#player-show').textContent=getEpisode(item.key)?.show_title||showName(item.show);$('#player-art').innerHTML=coverFor(item.show)?`<img src="${escapeHTML(coverFor(item.show))}" alt="">`:escapeHTML(showStyle(item.show).initials);}else if(position!==null)audio.currentTime=Math.min(position,audio.duration||position);if(play)await audio.play();}
async function listen(){const d=app.selected;if(!d)return;if(!d.downloaded){await queueDownload(d.key);return;}if(app.playing?.key===d.key&&!audio.paused)audio.pause();else await activate(d,null,true);}
async function jump(start){await activate(app.selected,start,true);}

document.addEventListener('click',guard(async event=>{const t=event.target.closest('button');if(!t)return;
  if(t.dataset.view){setFocus(false);app.show=null;app.view=t.dataset.view;app.limit=30;await loadLibrary();}
  if(t.dataset.show){setFocus(false);app.show=t.dataset.show;app.view='all';app.limit=30;await loadLibrary();}
  if(t.dataset.language){app.language=t.dataset.language;try{localStorage.setItem('subtitle-language',app.language);}catch{}renderTranscript();}
  if(t.hasAttribute('data-open-settings'))await openSettings();
  if(t.dataset.episode)await selectEpisode(t.dataset.episode);
  if(t.dataset.download)await queueDownload(t.dataset.download);
  if(t.dataset.rowPlay){await selectEpisode(t.dataset.rowPlay);await activate(app.selected,null,true);}
  if(t.dataset.retry){const job=app.jobRecords.find(j=>j.id===t.dataset.retry);if(job){await api('/api/job',{kind:job.english_ready?"translate":job.kind,show:job.show,episode:job.episode,asset:job.asset});await pollJobs();}}
  if(t.dataset.openMark){const b=app.library.bookmarks.find(b=>b.id===t.dataset.openMark);await selectEpisode(b.episode);await jump(b.start);}
  if(t.dataset.tab){app.followAfter=0;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b===t)));document.querySelectorAll('.tab-content').forEach(p=>p.hidden=p.id!=='tab-'+t.dataset.tab);}
  if(t.dataset.jump!==undefined){app.loop=null;$('#loop').hidden=true;await jump(Number(t.dataset.jump));}
  if(t.dataset.loop){const mark=app.selected.bookmarks.find(b=>b.id===t.dataset.loop);await jump(mark.start);app.loop={start:mark.start,end:mark.end};$('#loop').hidden=false;toast('正在循环这个片段');}
  if(t.dataset.delete){await api('/api/bookmark-delete',{...basePayload(app.selected),id:t.dataset.delete});app.selected.bookmarks=app.selected.bookmarks.filter(b=>b.id!==t.dataset.delete);renderMarks();await loadLibrary();toast('标记已删除');}
  if(t.classList.contains('close-dialog'))t.closest('dialog').close();
}));
$('#listen-btn').onclick=guard(listen);$('#more').onclick=()=>{app.limit+=30;renderList();};$('#search').oninput=()=>{app.limit=30;renderList();};$('#transcript-search').oninput=renderTranscript;
async function generateSubtitles(kind='transcribe'){const d=app.selected;if(!d?.downloaded)return;await api('/api/job',{kind,show:d.show,episode:d.key.split(':')[1],asset:d.asset});toast(kind==='translate'?'正在补齐中文':'已加入队列：识别英文后自动翻译中文');await pollJobs();}
$('#transcribe-btn').onclick=guard(()=>generateSubtitles());$('#generate-subtitles').onclick=guard(()=>generateSubtitles());$('#translate-btn').onclick=guard(()=>generateSubtitles('translate'));
$('#cancel-transcribe').onclick=guard(async()=>{const job=transcriptionJob();if(job){await api('/api/job-cancel',{id:job.id});toast('已取消，完成的部分仍保留');await pollJobs();}});
async function openSettings(){const settings=await api('/api/translation-settings');$('#translation-model').value=settings.model;$('#translation-key').value='';$('#key-status').textContent=settings.configured?'已保存密钥；留空即可沿用。':'尚未配置密钥。';$('#settings-dialog').showModal();}
$('#settings-form').onsubmit=guard(async event=>{event.preventDefault();await api('/api/translation-settings',{model:$('#translation-model').value,api_key:$('#translation-key').value.trim(),resume_pending:true});$('#translation-key').value='';$('#settings-dialog').close();toast('设置已保存，待翻译字幕已加入队列');await pollJobs();});
$('#show-filter').onchange=guard(async()=>{app.show=$('#show-filter').value||null;if(app.view!=='vocabulary')app.view='all';app.limit=30;await loadLibrary();});
$('#save-notes').onclick=guard(()=>saveNotes());let noteTimeout;$('#notes').oninput=()=>{app.dirty=true;$('#note-status').textContent='尚未保存';clearTimeout(noteTimeout);noteTimeout=setTimeout(guard(()=>saveNotes(true)),900);};
$('#mark-btn').onclick=guard(async()=>{if(!app.selected?.downloaded)return;await activate(app.selected);const t=audio.currentTime;$('#mark-start').value=clock(Math.max(0,t-15));$('#mark-end').value=clock(Math.max(1,t));$('#mark-note').value='';$('#mark-dialog').showModal();});
$('#mark-form').onsubmit=guard(async e=>{e.preventDefault();const start=parseClock($('#mark-start').value),end=parseClock($('#mark-end').value);if(end<=start)throw Error('结束时间需要晚于开始时间');if(Number.isFinite(audio.duration)&&end>audio.duration+1)throw Error('片段超出了本集音频长度');await api('/api/bookmark',{...basePayload(app.selected),start,end,note:$('#mark-note').value});$('#mark-dialog').close();const d=await api('/api/episode?key='+encodeURIComponent(app.selected.key));app.selected.bookmarks=d.bookmarks;renderMarks();await loadLibrary();toast('片段已保存');});
$('#import-btn').onclick=()=>$('#import-dialog').showModal();$('#import-form').onsubmit=guard(async e=>{e.preventDefault();const file=$('#transcript-file').files[0];if(!file)throw Error('请选择文件');if(file.size>2_000_000)throw Error('文件不能超过 2 MB');const text=await file.text();await api('/api/transcript',{...basePayload(app.selected),name:file.name,text,aligned:$('#aligned').checked});$('#import-dialog').close();const d=await api('/api/episode?key='+encodeURIComponent(app.selected.key));app.selected.transcript=d.transcript;renderTranscript();await loadLibrary();await generateSubtitles('translate');});
$('#back').onclick=()=>{if(app.playing)audio.currentTime=Math.max(0,audio.currentTime-10);};$('#forward').onclick=()=>{if(app.playing)audio.currentTime=Math.min(audio.duration||Infinity,audio.currentTime+10);};$('#speed').onchange=()=>{audio.playbackRate=Number($('#speed').value);void saveProgress();};
$('#timer').onclick=()=>{app.timerEnd=app.timerEnd?null:Date.now()+30*60*1000;$('#timer').textContent=app.timerEnd?'◷ 30:00 后停止':'◷ 30 分钟停止';toast(app.timerEnd?'将在 30 分钟后暂停播放':'已取消停止计时');};$('#loop').onclick=()=>{app.loop=null;$('#loop').hidden=true;};
audio.addEventListener('play',guard(async()=>{if(app.playing&&app.selected?.key!==app.playing.key)await selectEpisode(app.playing.key);$('#listen-btn').textContent='Ⅱ 暂停';setFocus(true);const cover=coverFor(app.playing.show);if(cover)$('#player-art').innerHTML=`<img src="${escapeHTML(cover)}" alt="">`;}));audio.addEventListener('pause',()=>{if(app.selected?.key===app.playing?.key)$('#listen-btn').textContent='▶ 继续听';void saveProgress();});audio.addEventListener('ended',()=>{app.loop=null;$('#loop').hidden=true;void saveProgress();});
audio.addEventListener('timeupdate',()=>{if(app.loop&&audio.currentTime>=app.loop.end)audio.currentTime=app.loop.start;syncSubtitle(true);});
audio.addEventListener('error',()=>{if(app.playing)toast('音频无法播放，请重新选择本集或检查文件',true);});
audio.addEventListener('seeked',()=>{void saveProgress();});
document.querySelector('.tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const tabs=[...document.querySelectorAll('[data-tab]')];const current=tabs.indexOf(document.activeElement);if(current<0)return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(current+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();tabs[next].click();});
setInterval(()=>{if(app.playing&&!audio.paused)void saveProgress();},5000);setInterval(()=>{if(!app.timerEnd)return;const remaining=(app.timerEnd-Date.now())/1000;if(remaining<=0){audio.pause();app.timerEnd=null;$('#timer').textContent='◷ 30 分钟停止';toast('今天的 30 分钟到了，音频已暂停');}else $('#timer').textContent=`◷ ${clock(remaining)} 后停止`;},1000);
window.addEventListener('pagehide',()=>{if(app.playing)fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':app.token},body:JSON.stringify({...basePayload(app.playing),position:audio.currentTime,speed:audio.playbackRate}),keepalive:true}).catch(()=>{});if(app.dirty&&app.selected?.asset)fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':app.token},body:JSON.stringify({...basePayload(app.selected),notes:$('#notes').value}),keepalive:true}).catch(()=>{});});
window.addEventListener('beforeunload',e=>{if(app.dirty){e.preventDefault();e.returnValue='';}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$(app.focus?'#transcript-search':'#search').focus();}if(e.key===' '&&document.activeElement===document.body&&app.playing){e.preventDefault();audio.paused?audio.play().catch(err=>toast(err.message,true)):audio.pause();}});
$('#sync-btn').onclick=guard(async()=>{const shows=app.show?[app.show]:app.library.shows.map(s=>s.id);for(const show of shows)await api('/api/job',{kind:'sync',show});toast('正在更新节目目录');await pollJobs();});
async function pollJobs(){if(app.polling)return;app.polling=true;try{
  const {jobs}=await api('/api/jobs');let refresh=false,changed=false;app.jobRecords=jobs;
  for(const job of jobs){const old=app.jobs.get(job.id);if(old!==job.status){changed=true;if(['succeeded','failed','waiting_key','cancelled'].includes(job.status)){refresh=true;if(old&&job.status==='succeeded')toast(`${showName(job.show)} ${{sync:'目录已更新',download:'音频已下载',transcribe:'双语字幕已保存',translate:'中文已补齐'}[job.kind]}`);}}app.jobs.set(job.id,job.status);}
  const visible=jobs.filter(j=>['queued','running','failed','waiting_key'].includes(j.status)&&(!app.focus||j.show+':'+j.episode===app.selected?.key)&&!jobs.some(newer=>newer.id!==j.id&&jobs.indexOf(newer)>jobs.indexOf(j)&&newer.show===j.show&&newer.kind===j.kind&&newer.episode===j.episode));
  $('#jobs').innerHTML=visible.slice(-3).map(j=>{const title=j.episode?getEpisode(j.show+':'+j.episode)?.title:null;return `<div class="job ${j.status==='failed'?'failed':''}"><strong>${escapeHTML(showName(j.show))}</strong> · ${j.stage==='translating'?'翻译中文':{sync:'更新目录',download:'下载音频',transcribe:'生成中英字幕',translate:'翻译中文'}[j.kind]} · ${{queued:'等待中',running:'进行中',failed:'未完成',waiting_key:'等待密钥'}[j.status]}${['transcribe','translate'].includes(j.kind)&&j.status==='running'?` ${j.progress||0}%`:''}${title?`<div class="job-title">${escapeHTML(title)}</div>`:''}${j.status==='failed'?`<button class="text-button" data-retry="${j.id}">继续</button>`:j.status==='waiting_key'?'<button class="text-button" data-open-settings>翻译设置</button>':''}${j.error?`<details><summary>详情</summary>${escapeHTML(j.error)}</details>`:''}</div>`;}).join('');
  if(refresh)await loadLibrary();else if(changed)renderList();if(app.selected&&(refresh||transcriptionJob())){const key=app.selected.key;const d=await api('/api/episode?key='+encodeURIComponent(key));if(app.selected?.key===key){if(!app.selected.downloaded&&d.downloaded){app.selected=d;renderDetail();}else if(app.selected.transcript?.id!==d.transcript?.id||app.selected.transcript?.translation?.completed!==d.transcript?.translation?.completed||app.selected.transcript?.translation?.status!==d.transcript?.translation?.status){app.selected.transcript=d.transcript;renderTranscript();}}}updateDownloadState();updateTranscriptionState();
}catch(e){$('#jobs').textContent='暂时连接不到本地服务，请稍后刷新。';}finally{app.polling=false;}}

async function start(){await loadLibrary();const requested=location.hash.startsWith('#listen=')?decodeURIComponent(location.hash.slice(8)):null;const local=app.library.episodes.filter(e=>e.downloaded).sort((a,b)=>b.updated-a.updated);if(requested&&getEpisode(requested)?.downloaded){await selectEpisode(requested);await activate(app.selected);setFocus(true);}else if(local.length)await selectEpisode(local[0].key);await pollJobs();setInterval(pollJobs,4000);
  const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [
    {name:'list_local_podcast_episodes',description:'List downloaded podcast episodes available in this local library.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>app.library.episodes.filter(e=>e.downloaded).map(e=>({key:e.key,title:e.title,position:e.position}))},
    {name:'open_local_podcast_episode',description:'Select a podcast episode in the visible learning panel. Does not start playback.',inputSchema:{type:'object',properties:{key:{type:'string'}},required:['key'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(!input||typeof input.key!=='string'||!getEpisode(input.key))throw Error('Unknown episode');await selectEpisode(input.key);return {key:app.selected.key,title:app.selected.title};}}
  ]){try{await context.registerTool(tool,{signal:lifecycle.signal});}catch{ /* Unsupported optional WebMCP cannot block the app. */ }}}
}
start().catch(e=>{$('#episodes').innerHTML='<div class="empty">资料库未能打开，请刷新页面或重新启动。</div>';toast(e.message,true);});
